CREATE ROLE detechtico_app LOGIN PASSWORD 'B4jH6Vt9Km3Zp2Wx7NqC'
  NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE detechtico TO detechtico_app;
GRANT USAGE ON SCHEMA public TO detechtico_app;

ALTER DEFAULT PRIVILEGES FOR ROLE detechtico IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO detechtico_app;
ALTER DEFAULT PRIVILEGES FOR ROLE detechtico IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO detechtico_app;
